import React, { Suspense } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Web3Provider from "./providers/Web3Provider";
import Loading from "./loading";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<Loading />}>
          <Web3Provider>
            <div className="bg-[#091B18] min-h-screen ">{children}</div>
          </Web3Provider>
        </Suspense>
      </body>
    </html>
  );
}
